# backend/docker-compose.yml
services:
  postgres:
    container_name: postgres-postgres-1
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: mandibula
      POSTGRES_PASSWORD: isopodes
      POSTGRES_DB: mandibula
    ports:
      - "5432:5432"
    volumes:
      - postgres-dbs:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mandibula"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-dbs: