name: CI

on:
  push:
    branches: [main, Auth]
  pull_request:
    branches: [main, Auth]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
